name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make CXX='g++' CXXFLAGS='-O3 -Wall -Werror -Wpedantic -std=c++20'
    - name: make check
      run: make check CXX='g++' CXXFLAGS='-O3 -Wall -Werror -Wpedantic -std=c++20'
